import { type StyleValue } from 'vue';
export interface SignatureProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    color?: string;
    lineWidth?: number;
    background?: string;
    fullScreen?: boolean;
    duration?: number;
    visible?: boolean;
    cancelText?: string;
    clearText?: string;
    confirmText?: string;
    customNavbar?: boolean;
    type?: 'png' | 'jpg';
    target?: 'dataURL' | 'filePath';
    quality?: number;
}
export declare const defaultSignatureProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string)) | undefined;
    color?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string)) | undefined;
    lineWidth?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => number)) | undefined;
    background?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string)) | undefined;
    fullScreen?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => boolean)) | undefined;
    duration?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => number)) | undefined;
    visible?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => boolean)) | undefined;
    cancelText?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string)) | undefined;
    clearText?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string)) | undefined;
    confirmText?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => string)) | undefined;
    customNavbar?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => boolean)) | undefined;
    type?: ("png" | "jpg" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => "png" | "jpg")) | undefined;
    target?: ("filePath" | "dataURL" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => "filePath" | "dataURL")) | undefined;
    quality?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        color: string;
        lineWidth: number;
        background: string;
        fullScreen: boolean;
        duration: number;
        visible: boolean;
        cancelText: string;
        clearText: string;
        confirmText: string;
        customNavbar: boolean;
        type: "png" | "jpg";
        target: "dataURL" | "filePath";
        quality: number;
    }) => number)) | undefined;
};
export interface SignatureSlots {
    default?(props: Record<string, never>): any;
}
export interface SignatureEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'confirm', dataURL: string): void;
    (e: 'clear'): void;
    (e: 'cancel'): void;
}
export interface SignatureExpose {
    resize: () => void;
    clear: () => void;
    confirm: () => void;
}
