import { type StyleValue } from 'vue';
import { type CascaderOption, type CascaderProps } from '../cascader/common';
import { type TransitionHookEmits } from '../popup/common';
export interface CascaderPopoutProps extends CascaderProps {
    visible?: boolean;
    title?: string;
    showConfirm?: boolean;
    validateEvent?: boolean;
    popoutClass?: string;
    popoutStyle?: StyleValue;
    resettable?: boolean;
}
export declare const defaultCascaderPopoutProps: {
    visible?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => boolean)) | undefined;
    title?: (string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string)) | undefined;
    showConfirm?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => boolean)) | undefined;
    validateEvent?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => boolean)) | undefined;
    popoutClass?: (string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string)) | undefined;
    popoutStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    resettable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => boolean)) | undefined;
    rootStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string)) | undefined;
    modelValue?: (string | number | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string | number | (string | number)[])) | undefined;
    options?: ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => CascaderOption[]) | undefined;
    fieldKeys?: ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => import("../cascader/common").CascaderFieldKeys) | undefined;
    hintText?: (string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => string)) | undefined;
    labelRender?: (((option: CascaderOption) => string) | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => (option: CascaderOption) => string)) | undefined;
    changeOnSelect?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => boolean)) | undefined;
    allLevels?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: CascaderOption[];
        fieldKeys: import("../cascader/common").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
    }) => boolean)) | undefined;
};
export interface CascaderPopoutSlots {
    top?(props: {
        tabIndex: number;
    }): any;
}
export interface CascaderPopoutEmits extends TransitionHookEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'update:model-value', value: any, selectedOptions: CascaderOption[]): void;
    (e: 'change', value: any, selectedOptions: CascaderOption[]): void;
    (e: 'select', option: CascaderOption, tabIndex: number): void;
    (e: 'confirm'): void;
}
export interface CascaderPopoutExpose {
}
