import { type StyleValue } from 'vue';
export interface SliderProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    range?: boolean;
    modelValue?: number | number[];
    min?: number;
    max?: number;
    step?: number;
    vertical?: boolean;
    disabled?: boolean;
    readonly?: boolean;
    pieceColor?: string;
    trackColor?: string;
    trackSize?: string;
    thumbColor?: string;
    thumbSize?: string;
    showValue?: boolean;
    valuePosition?: 'top' | 'right' | 'bottom' | 'left';
    valueBackground?: string;
    valueColor?: string;
    showScale?: boolean;
    scalePosition?: 'top' | 'right' | 'bottom' | 'left';
    validateEvent?: boolean;
}
export declare const defaultSliderProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    range?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
    modelValue?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => number | number[])) | undefined;
    min?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => number)) | undefined;
    max?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => number)) | undefined;
    step?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => number)) | undefined;
    vertical?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
    pieceColor?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    trackColor?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    trackSize?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    thumbColor?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    thumbSize?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    showValue?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
    valuePosition?: ("left" | "right" | "bottom" | "top" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => "left" | "right" | "bottom" | "top")) | undefined;
    valueBackground?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    valueColor?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => string)) | undefined;
    showScale?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
    scalePosition?: ("left" | "right" | "bottom" | "top" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => "left" | "right" | "bottom" | "top")) | undefined;
    validateEvent?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        range: boolean;
        modelValue: number | number[];
        min: number;
        max: number;
        step: number;
        vertical: boolean;
        disabled: boolean;
        readonly: boolean;
        pieceColor: string;
        trackColor: string;
        trackSize: string;
        thumbColor: string;
        thumbSize: string;
        showValue: boolean;
        valuePosition: "top" | "right" | "bottom" | "left";
        valueBackground: string;
        valueColor: string;
        showScale: boolean;
        scalePosition: "top" | "right" | "bottom" | "left";
        validateEvent: boolean;
    }) => boolean)) | undefined;
};
export interface SliderSlots {
    'start-thumb'?(props: {
        value: number;
    }): any;
    'end-thumb'?(props: {
        value: number;
    }): any;
}
export interface SliderEmits {
    (e: 'update:model-value', value: number | number[]): void;
    (e: 'input', value: number | number[]): void;
    (e: 'change', value: number | number[]): void;
    (e: 'drag-start', event: TouchEvent): void;
    (e: 'drag-end', event: TouchEvent): void;
}
