import { type StyleValue } from 'vue';
import { type CheckboxGroupProps } from '../checkbox/common';
import { type TransitionHookEmits } from '../popup/common';
export interface CheckboxPopoutProps extends CheckboxGroupProps {
    visible?: boolean;
    title?: string;
    popoutClass?: string;
    popoutStyle?: StyleValue;
    showCheckAll?: boolean;
    searchable?: boolean;
    filterPlaceholder?: string;
    resettable?: boolean;
    iconPosition?: 'left' | 'right';
}
export declare const defaultCheckboxPopoutProps: () => {
    options: () => never[];
    visible?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    title?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string)) | undefined;
    popoutClass?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string)) | undefined;
    popoutStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    showCheckAll?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    searchable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    filterPlaceholder?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string)) | undefined;
    resettable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    iconPosition?: ("left" | "right" | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => "left" | "right")) | undefined;
    rootStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string)) | undefined;
    modelValue?: ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => any[]) | undefined;
    disabled?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    size?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string)) | undefined;
    type?: (import("../checkbox/common").IconType | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => "circle" | "square")) | undefined;
    checkedColor?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => string)) | undefined;
    direction?: ("horizontal" | "vertical" | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => "horizontal" | "vertical")) | undefined;
    validateEvent?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => boolean)) | undefined;
    optionKeys?: ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../checkbox/common").CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
    }) => import("../checkbox/common").CheckboxGroupOptionKeys) | undefined;
};
export interface CheckboxPopoutSlots {
    default?(props: Record<string, never>): any;
}
export interface CheckboxPopoutEmits extends TransitionHookEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'update:model-value', value: any): void;
    (e: 'change', value: any): void;
    (e: 'confirm'): void;
}
export interface CheckboxPopoutExpose {
}
