import { type StyleValue } from 'vue';
import { type InputProps } from '../input';
export interface PopoutInputProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    modelValue?: any;
    placeholder?: string;
    readonly?: boolean;
    disabled?: boolean;
    clearable?: boolean;
    loading?: boolean;
    multiline?: boolean;
    arrow?: string;
    arrowFamily?: string;
    internalArrow?: number;
    inputProps?: InputProps;
}
export declare const defaultPopoutInputProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => string)) | undefined;
    modelValue?: any;
    placeholder?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => string)) | undefined;
    readonly?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => boolean)) | undefined;
    clearable?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => boolean)) | undefined;
    loading?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        placeholder: string;
        readonly: boolean;
        disabled: boolean;
        clearable: boolean;
        loading: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: InputProps;
    }) => InputProps) | undefined;
};
export interface PopoutInputEmits {
    (e: 'click', event: any): void;
    (e: 'update:model-value', value: string): void;
    (e: 'change', value: string): void;
    (e: 'clear'): void;
}
export interface PopoutInputSlots {
    'arrow'(): any;
}
