import { type RadioGroupOption } from '../radio/common';
import { type PopoutInputSlots, type PopoutInputProps } from '../popout-input/common';
import { type RadioPopoutEmits, type RadioPopoutProps } from '../radio-popout/common';
export type RadioInputOption = RadioGroupOption;
export interface RadioInputProps extends RadioPopoutProps, Omit<PopoutInputProps, 'modelValue'> {
    valueOnClear?: () => any;
}
export declare const defaultRadioInputProps: () => {
    valueOnClear?: ((() => any) | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => any)) | undefined;
    visible?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    title?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    searchable?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    filterPlaceholder?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    resettable?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    iconPosition?: "left" | "right" | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "left" | "right") | undefined;
    rootStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    modelValue?: any;
    disabled?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    readonly?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    size?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    type?: "circle" | "record" | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "circle" | "record") | undefined;
    checkedColor?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    direction?: "horizontal" | "vertical" | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "horizontal" | "vertical") | undefined;
    validateEvent?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    options: (props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => RadioGroupOption[];
    optionKeys?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../radio/common").RadioGroupOptionKeys) | undefined;
    loading?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    clearable?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../input").InputProps) | undefined;
};
export interface RadioInputSlots extends PopoutInputSlots {
}
export interface RadioInputEmits extends RadioPopoutEmits {
}
