import { type DatetimeRangePickerPopoutProps, type DatetimeRangePickerPopoutSlots, type DatetimeRangePickerPopoutEmits } from '../datetime-range-picker-popout/common';
import { type PopoutInputSlots, type PopoutInputProps } from '../popout-input/common';
export interface DatetimeRangePickerInputProps extends DatetimeRangePickerPopoutProps, Omit<PopoutInputProps, 'modelValue' | 'loading'> {
    outletFormat?: string;
    valueOnClear?: () => any;
}
export declare const defaultDatetimeRangePickerInputProps: () => {
    outletFormat?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    valueOnClear?: ((() => any) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => any)) | undefined;
    visible?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    title?: string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    validateEvent?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    popoutClass?: string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutStyle?: string | false | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    resettable?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    modelValue?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => (string | Date)[]) | undefined;
    tabs?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string[]) | undefined;
    filter?: (((letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean)) | undefined;
    min?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | Date)) | undefined;
    max?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | Date)) | undefined;
    rootStyle?: (string | false | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    type?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    calendar?: ("solar" | "lunar" | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "solar" | "lunar")) | undefined;
    formatter?: (((letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined)) | undefined;
    valueFormat?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    disabled?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    clearable?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../input").InputProps) | undefined;
};
export interface DatetimeRangePickerInputSlots extends DatetimeRangePickerPopoutSlots, PopoutInputSlots {
}
export interface DatetimeRangePickerInputEmits extends DatetimeRangePickerPopoutEmits {
}
