import { type StyleValue } from 'vue';
export interface RateProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    modelValue?: number;
    allowHalf?: boolean;
    clearable?: boolean;
    count?: number;
    size?: string;
    gap?: string;
    iconFamily?: string;
    icon?: string;
    voidIcon?: string;
    text?: string;
    voidText?: string;
    color?: string;
    voidColor?: string;
    disabled?: boolean;
    readonly?: boolean;
    validateEvent?: boolean;
}
export declare const defaultRateProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    modelValue?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => number)) | undefined;
    allowHalf?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    clearable?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    count?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => number)) | undefined;
    size?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    gap?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    iconFamily?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    icon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    voidIcon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    text?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    voidText?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    color?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    voidColor?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    validateEvent?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number;
        allowHalf: boolean;
        clearable: boolean;
        count: number;
        size: string;
        gap: string;
        iconFamily: string;
        icon: string;
        voidIcon: string;
        text: string;
        voidText: string;
        color: string;
        voidColor: string;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
};
export interface RateEmits {
    (e: 'update:model-value', value: number): void;
    (e: 'change', value: number): void;
}
