import { type StyleValue } from 'vue';
export interface PasswordInputProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    modelValue?: string;
    length?: number;
    type?: 'border' | 'underline';
    gap?: number | string;
    plainText?: boolean;
    focused?: boolean;
    customKeyboard?: boolean;
    disabled?: boolean;
    readonly?: boolean;
    validateEvent?: boolean;
}
export declare const defaultPasswordInputProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    modelValue?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string)) | undefined;
    length?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => number)) | undefined;
    type?: ("border" | "underline" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => "border" | "underline")) | undefined;
    gap?: (string | number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => string | number)) | undefined;
    plainText?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    focused?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    customKeyboard?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
    validateEvent?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        length: number;
        type: "border" | "underline";
        gap: number | string;
        plainText: boolean;
        focused: boolean;
        customKeyboard: boolean;
        disabled: boolean;
        readonly: boolean;
        validateEvent: boolean;
    }) => boolean)) | undefined;
};
export interface PasswordInputEmits {
    (e: 'update:model-value', value: string): void;
    (e: 'change', value: string): void;
    (e: 'updat:focused', focused: boolean): void;
}
