import { type StyleValue } from 'vue';
import { type DatetimePickerProps, type DatetimePickerSlots } from '../datetime-picker/common';
import { type TransitionHookEmits } from '../popup/common';
export interface DatetimePickerPopoutProps extends DatetimePickerProps {
    visible?: boolean;
    title?: string;
    validateEvent?: boolean;
    popoutClass?: string;
    popoutStyle?: StyleValue;
    resettable?: boolean;
}
export declare const defaultDatetimePickerPopoutProps: () => {
    visible?: (boolean | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => boolean)) | undefined;
    title?: (string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string)) | undefined;
    validateEvent?: (boolean | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => boolean)) | undefined;
    popoutClass?: (string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string)) | undefined;
    popoutStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    resettable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => boolean)) | undefined;
    rootStyle?: string | false | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string) | undefined;
    type?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string) | undefined;
    calendar?: "solar" | "lunar" | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => "solar" | "lunar") | undefined;
    min?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | Date) | undefined;
    max?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | Date) | undefined;
    modelValue?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | Date) | undefined;
    filter?: ((letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean) | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean) | undefined;
    formatter?: ((letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined) | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined) | undefined;
    valueFormat?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        min: Date | string;
        max: Date | string;
        modelValue: Date | string;
        filter: (letter: import("../datetime-picker/common").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        formatter: (letter: import("../datetime-picker/common").DatetimeLetter, option: import("../datetime-picker/common").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string) | undefined;
};
export interface DatetimePickerPopoutSlots extends DatetimePickerSlots {
}
export interface DatetimePickerPopoutEmits extends TransitionHookEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'update:model-value', date: Date | string | undefined): void;
    (e: 'change', date: Date | string | undefined): void;
    (e: 'confirm'): void;
}
export interface DatetimePickerPopoutExpose {
}
