import { type DialogEmits, type DialogProps } from '../dialog/common';
import { type TransitionHookCallbacks } from '../popup/common';
export interface DialogAgentProps extends DialogProps, TransitionHookCallbacks {
    id?: string;
    onClose?: () => void;
    onCancel?: () => void;
    onConfirm?: () => void;
}
export declare const defaultDialogAgentProps: () => {
    id?: (string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string)) | undefined;
    onClose?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onCancel?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onConfirm?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    rootStyle?: string | false | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string) | undefined;
    popupStyle?: string | false | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    popupClass?: string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string) | undefined;
    visible?: boolean | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => boolean) | undefined;
    title?: string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string) | undefined;
    message?: string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string) | undefined;
    headed?: boolean | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => boolean) | undefined;
    buttonType?: "text" | "round" | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => "text" | "round") | undefined;
    showCancel?: boolean | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => boolean) | undefined;
    cancelText?: string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string) | undefined;
    showConfirm?: boolean | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => boolean) | undefined;
    confirmText?: string | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => string) | undefined;
    overlayClosable?: boolean | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => boolean) | undefined;
    beforeClose?: import("../dialog/common").DialogBeforeClose | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => import("../dialog/common").DialogBeforeClose) | undefined;
    duration?: number | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => number) | undefined;
    cancelProps?: ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => import("../button").ButtonProps) | undefined;
    confirmProps?: ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => import("../button").ButtonProps) | undefined;
    onVisibleHook?: (((name: import("../../use").TransitionHookName) => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => (name: import("../../use").TransitionHookName) => void)) | undefined;
    onBeforeEnter?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onEnter?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onAfterEnter?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onEnterCancelled?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onBeforeLeave?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onLeave?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onAfterLeave?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
    onLeaveCancelled?: ((() => void) | ((props: {
        id: string;
        onClose: () => void;
        onCancel: () => void;
        onConfirm: () => void;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        popupStyle: import("vue").StyleValue;
        popupClass: string;
        visible: boolean;
        title: string;
        message: string;
        headed: boolean;
        buttonType: "round" | "text";
        showCancel: boolean;
        cancelText: string;
        showConfirm: boolean;
        confirmText: string;
        overlayClosable: boolean;
        beforeClose: import("../dialog/common").DialogBeforeClose;
        duration: number;
        cancelProps: import("../button").ButtonProps;
        confirmProps: import("../button").ButtonProps;
        onVisibleHook: (name: import("../../use").TransitionHookName) => void;
        onBeforeEnter: () => void;
        onEnter: () => void;
        onAfterEnter: () => void;
        onEnterCancelled: () => void;
        onBeforeLeave: () => void;
        onLeave: () => void;
        onAfterLeave: () => void;
        onLeaveCancelled: () => void;
    }) => () => void)) | undefined;
};
export interface DialogAgentEmits extends DialogEmits {
}
export declare const imperativeName = "dialog";
export interface DialogImperative {
    show(newProps: Record<string, any>): void;
    hide(): void;
}
export type DialogOptions = DialogAgentProps;
export interface DialogSimpleShowFunction {
    (options: DialogOptions): void;
    (title: string, options?: DialogOptions): void;
}
export interface DialogShowFunction {
    (optionsOrTitle: string | DialogOptions, options?: DialogOptions, internalOptions?: DialogOptions): void;
}
export type DialogFunction = DialogSimpleShowFunction & {
    alert: DialogSimpleShowFunction;
    confirm: DialogSimpleShowFunction;
    hide: (id?: string) => void;
    hideAll: () => void;
};
declare const dialog: DialogFunction;
export { dialog };
