import { type StyleValue } from 'vue';
export interface InputProps {
    enableNative?: boolean;
    placeholder?: string;
    placeholderStyle?: string;
    placeholderClass?: string;
    disabled?: boolean;
    maxlength?: number;
    focus?: boolean;
    cursorSpacing?: number;
    cursor?: number;
    confirmType?: 'send' | 'search' | 'next' | 'go' | 'done';
    confirmHold?: boolean;
    selectionStart?: number;
    selectionEnd?: number;
    adjustPosition?: boolean;
    holdKeyboard?: boolean;
    autoBlur?: boolean;
    ignoreCompositionEvent?: boolean;
    inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
    autoHeight?: boolean;
    fixed?: boolean;
    showConfirmBar?: boolean;
    disableDefaultPadding?: boolean;
    inputMinHeight?: boolean;
    type?: 'text' | 'number' | 'idcard' | 'digit' | 'tel' | 'safe-password' | 'nickname' | 'password' | 'textarea';
    alwaysEmbed?: boolean;
    safePasswordCertPath?: string;
    safePasswordLength?: string;
    safePasswordTimeStamp?: string;
    safePasswordNonce?: string;
    safePasswordSalt?: string;
    safePasswordCustomHash?: string;
    randomNumber?: boolean;
    controlled?: boolean;
    alwaysSystem?: boolean;
    rootClass?: string;
    rootStyle?: StyleValue;
    modelValue?: string | number;
    clearable?: boolean;
    showClearOnlyFocus?: boolean;
    showCount?: boolean;
    inlaid?: boolean;
    borderless?: boolean;
    readonly?: boolean;
    focused?: boolean;
    minHeight?: string;
    validateEvent?: boolean;
    showEye?: boolean;
    internalPrepend?: number;
}
export declare const defaultInputProps: {
    enableNative?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    placeholderStyle?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    placeholderClass?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    disabled?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    maxlength?: (number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => number)) | undefined;
    focus?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    cursorSpacing?: (number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => number)) | undefined;
    cursor?: (number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => number)) | undefined;
    confirmType?: ("done" | "search" | "send" | "next" | "go" | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => "done" | "search" | "send" | "next" | "go")) | undefined;
    confirmHold?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    selectionStart?: (number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => number)) | undefined;
    selectionEnd?: (number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => number)) | undefined;
    adjustPosition?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    holdKeyboard?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    autoBlur?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    ignoreCompositionEvent?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    inputmode?: ("text" | "url" | "search" | "email" | "none" | "decimal" | "numeric" | "tel" | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => "text" | "url" | "search" | "email" | "none" | "decimal" | "numeric" | "tel")) | undefined;
    autoHeight?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    fixed?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    showConfirmBar?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    disableDefaultPadding?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    inputMinHeight?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    type?: ("number" | "text" | "textarea" | "tel" | "idcard" | "digit" | "safe-password" | "nickname" | "password" | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => "number" | "text" | "textarea" | "tel" | "idcard" | "digit" | "safe-password" | "nickname" | "password")) | undefined;
    alwaysEmbed?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    safePasswordCertPath?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    safePasswordLength?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    safePasswordTimeStamp?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    safePasswordNonce?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    safePasswordSalt?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    safePasswordCustomHash?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    randomNumber?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    controlled?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    alwaysSystem?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    rootClass?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    rootStyle?: (string | false | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    modelValue?: (string | number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string | number)) | undefined;
    clearable?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    showClearOnlyFocus?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    showCount?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    inlaid?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    borderless?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    focused?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    minHeight?: (string | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => string)) | undefined;
    validateEvent?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    showEye?: (boolean | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => boolean)) | undefined;
    internalPrepend?: (number | ((props: {
        enableNative: boolean;
        placeholder: string;
        placeholderStyle: string;
        placeholderClass: string;
        disabled: boolean;
        maxlength: number;
        focus: boolean;
        cursorSpacing: number;
        cursor: number;
        confirmType: "send" | "search" | "next" | "go" | "done";
        confirmHold: boolean;
        selectionStart: number;
        selectionEnd: number;
        adjustPosition: boolean;
        holdKeyboard: boolean;
        autoBlur: boolean;
        ignoreCompositionEvent: boolean;
        inputmode: "none" | "text" | "decimal" | "numeric" | "tel" | "search" | "email" | "url";
        autoHeight: boolean;
        fixed: boolean;
        showConfirmBar: boolean;
        disableDefaultPadding: boolean;
        inputMinHeight: boolean;
        type: "text" | "number" | "idcard" | "digit" | "tel" | "safe-password" | "nickname" | "password" | "textarea";
        alwaysEmbed: boolean;
        safePasswordCertPath: string;
        safePasswordLength: string;
        safePasswordTimeStamp: string;
        safePasswordNonce: string;
        safePasswordSalt: string;
        safePasswordCustomHash: string;
        randomNumber: boolean;
        controlled: boolean;
        alwaysSystem: boolean;
        rootClass: string;
        rootStyle: StyleValue;
        modelValue: string | number;
        clearable: boolean;
        showClearOnlyFocus: boolean;
        showCount: boolean;
        inlaid: boolean;
        borderless: boolean;
        readonly: boolean;
        focused: boolean;
        minHeight: string;
        validateEvent: boolean;
        showEye: boolean;
        internalPrepend: number;
    }) => number)) | undefined;
};
export interface InputSlots {
    prepend?(props: Record<string, never>): any;
    append?(props: Record<string, never>): any;
    addon?(props: Record<string, never>): any;
}
export interface InputEmits {
    (e: 'update:model-value', value: string): void;
    (e: 'change', value: string): void;
    (e: 'input', value: string): void;
    (e: 'clear'): void;
    (e: 'focus', event: any): void;
    (e: 'blur', event: any): void;
    (e: 'linechange', event: any): void;
    (e: 'confirm', event: any): void;
    (e: 'keyboardheightchange', event: any): void;
    (e: 'click', event: any): void;
}
