import { type StyleValue } from 'vue';
import { type RadioGroupProps } from '../radio/common';
import { type TransitionHookEmits } from '../popup/common';
export interface RadioPopoutProps extends RadioGroupProps {
    visible?: boolean;
    title?: string;
    popoutClass?: string;
    popoutStyle?: StyleValue;
    searchable?: boolean;
    filterPlaceholder?: string;
    resettable?: boolean;
    iconPosition?: 'left' | 'right';
}
export declare const defaultRadioPopoutProps: () => {
    options: () => never[];
    visible?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => boolean)) | undefined;
    title?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string)) | undefined;
    popoutClass?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string)) | undefined;
    popoutStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    searchable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => boolean)) | undefined;
    filterPlaceholder?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string)) | undefined;
    resettable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => boolean)) | undefined;
    iconPosition?: ("left" | "right" | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => "left" | "right")) | undefined;
    rootStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string)) | undefined;
    modelValue?: any;
    disabled?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => boolean)) | undefined;
    size?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string)) | undefined;
    type?: (import("../radio/common").IconType | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => "circle" | "record")) | undefined;
    checkedColor?: (string | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => string)) | undefined;
    direction?: ("horizontal" | "vertical" | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => "horizontal" | "vertical")) | undefined;
    validateEvent?: (boolean | ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => boolean)) | undefined;
    optionKeys?: ((props: {
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: StyleValue;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: any;
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../radio/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: import("../radio/common").RadioGroupOption[];
        optionKeys: import("../radio/common").RadioGroupOptionKeys;
    }) => import("../radio/common").RadioGroupOptionKeys) | undefined;
};
export interface RadioPopoutSlots {
    default?(props: Record<string, never>): any;
}
export interface RadioPopoutEmits extends TransitionHookEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'update:model-value', value: any): void;
    (e: 'change', value: any): void;
    (e: 'confirm'): void;
}
export interface RadioPopoutExpose {
}
