import { type StyleValue } from 'vue';
import { type CalendarProps } from '../calendar/common';
import { type TransitionHookEmits } from '../popup/common';
export interface CalendarPopoutProps extends CalendarProps {
    visible?: boolean;
    title?: string;
    showConfirm?: boolean;
    validateEvent?: boolean;
    popoutClass?: string;
    popoutStyle?: StyleValue;
    resettable?: boolean;
}
export declare const defaultCalendarPopoutProps: () => {
    visible?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => boolean)) | undefined;
    title?: (string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string)) | undefined;
    showConfirm?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => boolean)) | undefined;
    validateEvent?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => boolean)) | undefined;
    popoutClass?: (string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string)) | undefined;
    popoutStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    resettable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => boolean)) | undefined;
    rootStyle?: string | false | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string) | undefined;
    type?: "multiple" | "single" | "range" | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => "multiple" | "single" | "range") | undefined;
    modelValue?: string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string | string[] | Date | Date[]) | undefined;
    min?: ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => Date) | undefined;
    max?: ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => Date) | undefined;
    currentDate?: ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => Date) | undefined;
    disabledDate?: ((date: Date) => boolean) | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => (date: Date) => boolean) | undefined;
    maxDays?: number | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => number) | undefined;
    overMaxDays?: (() => void) | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => () => void) | undefined;
    weekStartsOn?: number | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => number) | undefined;
    formatter?: ((day: import("../calendar/common").CalendarDay) => void) | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => (day: import("../calendar/common").CalendarDay) => void) | undefined;
    allowSameDay?: boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => boolean) | undefined;
    severalMonths?: boolean | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => boolean) | undefined;
    valueFormat?: string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string) | undefined;
    startDateText?: string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string) | undefined;
    endDateText?: string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string) | undefined;
    sameDateText?: string | ((props: {
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        rootStyle: StyleValue;
        rootClass: string;
        type: import("../calendar/common").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar/common").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
    }) => string) | undefined;
};
export interface CalendarPopoutSlots {
    default?(props: Record<string, never>): any;
    title?(props: Record<string, never>): any;
    'title-prepend'?(props: Record<string, never>): any;
}
export interface CalendarPopoutEmits extends TransitionHookEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'update:model-value', value: Date | Date[] | string | string[] | undefined): void;
    (e: 'change', value: Date | Date[] | string | string[] | undefined): void;
    (e: 'confirm'): void;
}
export interface CalendarPopoutExpose {
}
