import { InjectionKey, type StyleValue } from 'vue';
export type StepsStatus = 'wait' | 'process' | 'error' | 'finish';
export interface StepsItem {
    status?: StepsStatus;
    name?: string;
    description?: string;
}
export interface StepsProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    current?: number;
    itemList?: StepsItem[];
    center?: boolean;
    direction?: 'vertical' | 'horizontal';
    reverse?: boolean;
    status?: StepsStatus;
    iconFamily?: string;
    iconSize?: string;
    finishIcon?: string;
    processIcon?: string;
    waitIcon?: string;
    errorIcon?: string;
}
export declare const defaultStepsProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
    current?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => number)) | undefined;
    itemList?: ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => StepsItem[]) | undefined;
    center?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => boolean)) | undefined;
    direction?: ("horizontal" | "vertical" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => "horizontal" | "vertical")) | undefined;
    reverse?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => boolean)) | undefined;
    status?: (StepsStatus | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => "error" | "finish" | "wait" | "process")) | undefined;
    iconFamily?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
    iconSize?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
    finishIcon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
    processIcon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
    waitIcon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
    errorIcon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        current: number;
        itemList: StepsItem[];
        center: boolean;
        direction: "vertical" | "horizontal";
        reverse: boolean;
        status: StepsStatus;
        iconFamily: string;
        iconSize: string;
        finishIcon: string;
        processIcon: string;
        waitIcon: string;
        errorIcon: string;
    }) => string)) | undefined;
};
export interface StepsSlots {
    default?(props: Record<string, never>): any;
}
export interface StepsContext {
    current: number;
    center?: boolean;
    direction?: StepsProps['direction'];
    iconFamily?: string;
    iconSize?: string;
    finishIcon?: string;
    processIcon?: string;
    waitIcon?: string;
    errorIcon?: string;
    status?: StepsStatus;
    reverse?: boolean;
}
export declare const stepsContextSymbol: InjectionKey<StepsContext>;
