import { type StyleValue } from 'vue';
export interface StepperProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    modelValue?: number | string | null;
    min?: number;
    max?: number;
    valueOnClear?: number | 'min' | 'max';
    step?: number;
    precision?: number;
    inputStyle?: string;
    inputType?: 'number' | 'digit' | 'text';
    placeholder?: string;
    disabled?: boolean;
    readonly?: boolean;
    press?: boolean;
    pressTime?: number;
    interval?: number;
    validateEvent?: boolean;
    size?: 'small' | 'medium';
}
export declare const defaultStepperProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => string)) | undefined;
    modelValue?: (string | number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => string | number) | null) | undefined;
    min?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number)) | undefined;
    max?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number)) | undefined;
    valueOnClear?: (number | "min" | "max" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number | "min" | "max")) | undefined;
    step?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number)) | undefined;
    precision?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number)) | undefined;
    inputStyle?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => string)) | undefined;
    inputType?: ("number" | "text" | "digit" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => "number" | "text" | "digit")) | undefined;
    placeholder?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => string)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => boolean)) | undefined;
    press?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => boolean)) | undefined;
    pressTime?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number)) | undefined;
    interval?: (number | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => number)) | undefined;
    validateEvent?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => boolean)) | undefined;
    size?: ("small" | "medium" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: number | string | null;
        min: number;
        max: number;
        valueOnClear: number | "min" | "max";
        step: number;
        precision: number;
        inputStyle: string;
        inputType: "number" | "digit" | "text";
        placeholder: string;
        disabled: boolean;
        readonly: boolean;
        press: boolean;
        pressTime: number;
        interval: number;
        validateEvent: boolean;
        size: "small" | "medium";
    }) => "small" | "medium")) | undefined;
};
export interface StepperEmits {
    (e: 'update:model-value', value: number | string | undefined): void;
    (e: 'change', value: number | string | undefined): void;
    (e: 'focus', event: any): void;
    (e: 'blur', event: any): void;
}
