import { type StyleValue } from 'vue';
export interface ButtonProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    type?: 'default' | 'pale' | 'mild' | 'outline' | 'text' | 'pale-text';
    theme?: 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger' | 'neutral';
    size?: 'mini' | 'small' | 'medium' | 'large';
    round?: boolean;
    square?: boolean;
    disabled?: boolean;
    loading?: boolean;
    loadingType?: 'clock' | 'circular';
    color?: string;
    background?: string;
    block?: boolean;
    inline?: boolean;
    icon?: string;
    iconFamily?: string;
    iconSize?: string;
    formType?: string;
    openType?: string;
    appParameter?: string;
    hoverStopPropagation?: boolean;
    lang?: string;
    sessionFrom?: string;
    sendMessageTitle?: string;
    sendMessagePath?: string;
    sendMessageImg?: string;
    showMessageCard?: boolean;
    groupId?: string;
    guildId?: string;
    publicId?: string;
}
export declare const defaultButtonProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    type?: ("text" | "default" | "pale" | "mild" | "outline" | "pale-text" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => "text" | "default" | "pale" | "mild" | "outline" | "pale-text")) | undefined;
    theme?: ("success" | "primary" | "warning" | "danger" | "secondary" | "info" | "neutral" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => "success" | "primary" | "warning" | "danger" | "secondary" | "info" | "neutral")) | undefined;
    size?: ("small" | "mini" | "medium" | "large" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => "small" | "mini" | "medium" | "large")) | undefined;
    round?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    square?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    loading?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    loadingType?: ("clock" | "circular" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => "clock" | "circular")) | undefined;
    color?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    background?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    block?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    inline?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    icon?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    iconFamily?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    iconSize?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    formType?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    openType?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    appParameter?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    hoverStopPropagation?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    lang?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    sessionFrom?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    sendMessageTitle?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    sendMessagePath?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    sendMessageImg?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    showMessageCard?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => boolean)) | undefined;
    groupId?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    guildId?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
    publicId?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        type: "default" | "pale" | "mild" | "outline" | "text" | "pale-text";
        theme: "primary" | "secondary" | "success" | "info" | "warning" | "danger" | "neutral";
        size: "mini" | "small" | "medium" | "large";
        round: boolean;
        square: boolean;
        disabled: boolean;
        loading: boolean;
        loadingType: "clock" | "circular";
        color: string;
        background: string;
        block: boolean;
        inline: boolean;
        icon: string;
        iconFamily: string;
        iconSize: string;
        formType: string;
        openType: string;
        appParameter: string;
        hoverStopPropagation: boolean;
        lang: string;
        sessionFrom: string;
        sendMessageTitle: string;
        sendMessagePath: string;
        sendMessageImg: string;
        showMessageCard: boolean;
        groupId: string;
        guildId: string;
        publicId: string;
    }) => string)) | undefined;
};
export interface ButtonSlots {
    default?(props: Record<string, never>): any;
}
export interface ButtonEmits {
    (e: 'click', event: any): void;
    (e: 'getphonenumber', event: any): void;
    (e: 'getuserinfo', event: any): void;
    (e: 'error', event: any): void;
    (e: 'opensetting', event: any): void;
    (e: 'launchapp', event: any): void;
    (e: 'contact', event: any): void;
    (e: 'chooseavatar', event: any): void;
    (e: 'agreeprivacyauthorization', event: any): void;
    (e: 'addgroupapp', event: any): void;
    (e: 'chooseaddress', event: any): void;
    (e: 'chooseinvoicetitle', event: any): void;
    (e: 'subscribe', event: any): void;
    (e: 'login', event: any): void;
}
