declare module 'vue' {
  export interface GlobalComponents {
    SarAccordion: typeof import('./components/accordion/accordion').default
    SarAccordionItem: typeof import('./components/accordion-item/accordion-item').default
    SarActionSheet: typeof import('./components/action-sheet/action-sheet').default
    SarAlert: typeof import('./components/alert/alert').default
    SarAvatar: typeof import('./components/avatar/avatar').default
    SarAvatarGroup: typeof import('./components/avatar-group/avatar-group').default
    SarBackTop: typeof import('./components/back-top/back-top').default
    SarBadge: typeof import('./components/badge/badge').default
    SarButton: typeof import('./components/button/button').default
    SarCalendar: typeof import('./components/calendar/calendar').default
    SarCalendarInput: typeof import('./components/calendar-input/calendar-input').default
    SarCalendarPopout: typeof import('./components/calendar-popout/calendar-popout').default
    SarCard: typeof import('./components/card/card').default
    SarCascader: typeof import('./components/cascader/cascader').default
    SarCascaderInput: typeof import('./components/cascader-input/cascader-input').default
    SarCascaderPopout: typeof import('./components/cascader-popout/cascader-popout').default
    SarCheckbox: typeof import('./components/checkbox/checkbox').default
    SarCheckboxGroup: typeof import('./components/checkbox-group/checkbox-group').default
    SarCheckboxInput: typeof import('./components/checkbox-input/checkbox-input').default
    SarCheckboxPopout: typeof import('./components/checkbox-popout/checkbox-popout').default
    SarCol: typeof import('./components/col/col').default
    SarCollapse: typeof import('./components/collapse/collapse').default
    SarCoolIcon: typeof import('./components/cool-icon/cool-icon').default
    SarCountDown: typeof import('./components/count-down/count-down').default
    SarCountTo: typeof import('./components/count-to/count-to').default
    SarCropImage: typeof import('./components/crop-image/crop-image').default
    SarCropImageAgent: typeof import('./components/crop-image-agent/crop-image-agent').default
    SarDatetimePicker: typeof import('./components/datetime-picker/datetime-picker').default
    SarDatetimePickerInput: typeof import('./components/datetime-picker-input/datetime-picker-input').default
    SarDatetimePickerPopout: typeof import('./components/datetime-picker-popout/datetime-picker-popout').default
    SarDatetimeRangePicker: typeof import('./components/datetime-range-picker/datetime-range-picker').default
    SarDatetimeRangePickerInput: typeof import('./components/datetime-range-picker-input/datetime-range-picker-input').default
    SarDatetimeRangePickerPopout: typeof import('./components/datetime-range-picker-popout/datetime-range-picker-popout').default
    SarDialog: typeof import('./components/dialog/dialog').default
    SarDialogAgent: typeof import('./components/dialog-agent/dialog-agent').default
    SarDivider: typeof import('./components/divider/divider').default
    SarDnd: typeof import('./components/dnd/dnd').default
    SarDndHandle: typeof import('./components/dnd-handle/dnd-handle').default
    SarDndItem: typeof import('./components/dnd-item/dnd-item').default
    SarDropdown: typeof import('./components/dropdown/dropdown').default
    SarDropdownItem: typeof import('./components/dropdown-item/dropdown-item').default
    SarEmpty: typeof import('./components/empty/empty').default
    SarFab: typeof import('./components/fab/fab').default
    SarFabItem: typeof import('./components/fab-item/fab-item').default
    SarFloatingBubble: typeof import('./components/floating-bubble/floating-bubble').default
    SarFloatingPanel: typeof import('./components/floating-panel/floating-panel').default
    SarForm: typeof import('./components/form/form').default
    SarFormItem: typeof import('./components/form-item/form-item').default
    SarFormItemPlain: typeof import('./components/form-item-plain/form-item-plain').default
    SarFormPlain: typeof import('./components/form-plain/form-plain').default
    SarGrid: typeof import('./components/grid/grid').default
    SarGridItem: typeof import('./components/grid-item/grid-item').default
    SarIcon: typeof import('./components/icon/icon').default
    SarImage: typeof import('./components/image/image').default
    SarIndexes: typeof import('./components/indexes/indexes').default
    SarIndexesAnchor: typeof import('./components/indexes-anchor/indexes-anchor').default
    SarInput: typeof import('./components/input/input').default
    SarKeyboard: typeof import('./components/keyboard/keyboard').default
    SarList: typeof import('./components/list/list').default
    SarListItem: typeof import('./components/list-item/list-item').default
    SarLoadMore: typeof import('./components/load-more/load-more').default
    SarLoading: typeof import('./components/loading/loading').default
    SarMarquee: typeof import('./components/marquee/marquee').default
    SarMenu: typeof import('./components/menu/menu').default
    SarNavbar: typeof import('./components/navbar/navbar').default
    SarNavbarItem: typeof import('./components/navbar-item/navbar-item').default
    SarNavbarPit: typeof import('./components/navbar-pit/navbar-pit').default
    SarNoticeBar: typeof import('./components/notice-bar/notice-bar').default
    SarNotify: typeof import('./components/notify/notify').default
    SarNotifyAgent: typeof import('./components/notify-agent/notify-agent').default
    SarOverlay: typeof import('./components/overlay/overlay').default
    SarPagination: typeof import('./components/pagination/pagination').default
    SarPasswordInput: typeof import('./components/password-input/password-input').default
    SarPicker: typeof import('./components/picker/picker').default
    SarPickerInput: typeof import('./components/picker-input/picker-input').default
    SarPickerItem: typeof import('./components/picker-item/picker-item').default
    SarPickerPopout: typeof import('./components/picker-popout/picker-popout').default
    SarPopout: typeof import('./components/popout/popout').default
    SarPopoutInput: typeof import('./components/popout-input/popout-input').default
    SarPopover: typeof import('./components/popover/popover').default
    SarPopoverReference: typeof import('./components/popover-reference/popover-reference').default
    SarPopup: typeof import('./components/popup/popup').default
    SarProgressBar: typeof import('./components/progress-bar/progress-bar').default
    SarProgressCircle: typeof import('./components/progress-circle/progress-circle').default
    SarPullDownRefresh: typeof import('./components/pull-down-refresh/pull-down-refresh').default
    SarQrcode: typeof import('./components/qrcode/qrcode').default
    SarRadio: typeof import('./components/radio/radio').default
    SarRadioGroup: typeof import('./components/radio-group/radio-group').default
    SarRadioInput: typeof import('./components/radio-input/radio-input').default
    SarRadioPopout: typeof import('./components/radio-popout/radio-popout').default
    SarRate: typeof import('./components/rate/rate').default
    SarReadMore: typeof import('./components/read-more/read-more').default
    SarResizeSensor: typeof import('./components/resize-sensor/resize-sensor').default
    SarResult: typeof import('./components/result/result').default
    SarRow: typeof import('./components/row/row').default
    SarScrollList: typeof import('./components/scroll-list/scroll-list').default
    SarScrollSpy: typeof import('./components/scroll-spy/scroll-spy').default
    SarScrollSpyAnchor: typeof import('./components/scroll-spy-anchor/scroll-spy-anchor').default
    SarSearch: typeof import('./components/search/search').default
    SarSegmented: typeof import('./components/segmented/segmented').default
    SarSegmentedItem: typeof import('./components/segmented-item/segmented-item').default
    SarShareSheet: typeof import('./components/share-sheet/share-sheet').default
    SarSidebar: typeof import('./components/sidebar/sidebar').default
    SarSidebarItem: typeof import('./components/sidebar-item/sidebar-item').default
    SarSignature: typeof import('./components/signature/signature').default
    SarSkeleton: typeof import('./components/skeleton/skeleton').default
    SarSkeletonAvatar: typeof import('./components/skeleton-avatar/skeleton-avatar').default
    SarSkeletonBlock: typeof import('./components/skeleton-block/skeleton-block').default
    SarSkeletonParagraph: typeof import('./components/skeleton-paragraph/skeleton-paragraph').default
    SarSkeletonTitle: typeof import('./components/skeleton-title/skeleton-title').default
    SarSlider: typeof import('./components/slider/slider').default
    SarSpace: typeof import('./components/space/space').default
    SarStatusBar: typeof import('./components/status-bar/status-bar').default
    SarStep: typeof import('./components/step/step').default
    SarStepper: typeof import('./components/stepper/stepper').default
    SarSteps: typeof import('./components/steps/steps').default
    SarSticky: typeof import('./components/sticky/sticky').default
    SarStickyBox: typeof import('./components/sticky-box/sticky-box').default
    SarSwipeAction: typeof import('./components/swipe-action/swipe-action').default
    SarSwiperDot: typeof import('./components/swiper-dot/swiper-dot').default
    SarSwitch: typeof import('./components/switch/switch').default
    SarTab: typeof import('./components/tab/tab').default
    SarTabbar: typeof import('./components/tabbar/tabbar').default
    SarTabbarItem: typeof import('./components/tabbar-item/tabbar-item').default
    SarTabbarPit: typeof import('./components/tabbar-pit/tabbar-pit').default
    SarTable: typeof import('./components/table/table').default
    SarTableCell: typeof import('./components/table-cell/table-cell').default
    SarTableRow: typeof import('./components/table-row/table-row').default
    SarTabs: typeof import('./components/tabs/tabs').default
    SarTag: typeof import('./components/tag/tag').default
    SarTimeline: typeof import('./components/timeline/timeline').default
    SarTimelineItem: typeof import('./components/timeline-item/timeline-item').default
    SarToast: typeof import('./components/toast/toast').default
    SarToastAgent: typeof import('./components/toast-agent/toast-agent').default
    SarTree: typeof import('./components/tree/tree').default
    SarUpload: typeof import('./components/upload/upload').default
    SarWaterfall: typeof import('./components/waterfall/waterfall').default
    SarWaterfallItem: typeof import('./components/waterfall-item/waterfall-item').default
    SarWaterfallLoad: typeof import('./components/waterfall-load/waterfall-load').default
    SarWatermark: typeof import('./components/watermark/watermark').default
  }
}

export {}
