import { type PopoutInputSlots, type PopoutInputProps } from '../popout-input/common';
import { type PickerPopoutSlots, type PickerPopoutEmits, type PickerPopoutProps } from '../picker-popout/common';
export interface PickerInputProps extends PickerPopoutProps, Omit<PopoutInputProps, 'modelValue'> {
    valueOnClear?: () => any;
}
export declare const defaultPickerInputProps: () => {
    valueOnClear?: ((() => any) | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => any)) | undefined;
    visible?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    title?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    validateEvent?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    popoutClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    resettable?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    rootStyle?: (string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    columns: (props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../picker").PickerOption[] | import("../picker").PickerOption[][];
    optionKeys?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../picker").PickerOptionKeys) | undefined;
    modelValue?: any;
    immediateChange?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    internalCustom?: (number | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    loading?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    clearable?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        columns: import("../picker").PickerOption[] | import("../picker").PickerOption[][];
        optionKeys: import("../picker").PickerOptionKeys;
        modelValue: any;
        immediateChange: boolean;
        internalCustom: number;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../input").InputProps) | undefined;
};
export interface PickerInputSlots extends PickerPopoutSlots, PopoutInputSlots {
}
export interface PickerInputEmits extends PickerPopoutEmits {
}
