import { type StyleValue } from 'vue';
export interface SearchProps {
    rootStyle?: StyleValue;
    rootClass?: string;
    modelValue?: string;
    placeholder?: string;
    shape?: 'round' | 'square';
    background?: string;
    inputBackground?: string;
    inputColor?: string;
    readonly?: boolean;
    disabled?: boolean;
    align?: 'left' | 'center' | 'right';
    cancel?: string;
    search?: string;
    focus?: boolean;
}
export declare const defaultSearchProps: {
    rootStyle?: (string | false | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    modelValue?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    placeholder?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    shape?: ("square" | "round" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => "square" | "round")) | undefined;
    background?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    inputBackground?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    inputColor?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    readonly?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => boolean)) | undefined;
    align?: ("center" | "left" | "right" | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => "center" | "left" | "right")) | undefined;
    cancel?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    search?: (string | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => string)) | undefined;
    focus?: (boolean | ((props: {
        rootStyle: StyleValue;
        rootClass: string;
        modelValue: string;
        placeholder: string;
        shape: "round" | "square";
        background: string;
        inputBackground: string;
        inputColor: string;
        readonly: boolean;
        disabled: boolean;
        align: "left" | "center" | "right";
        cancel: string;
        search: string;
        focus: boolean;
    }) => boolean)) | undefined;
};
export interface SearchSlots {
    prepend?(props: Record<string, never>): any;
    append?(props: Record<string, never>): any;
    'input-prepend'?(props: Record<string, never>): any;
    'input-append'?(props: Record<string, never>): any;
}
export interface SearchEmits {
    (e: 'update:model-value', value: string): void;
    (e: 'input', value: string): void;
    (e: 'change', value: string): void;
    (e: 'cancel'): void;
    (e: 'search', value: string): void;
    (e: 'click', event: any): void;
    (e: 'clear'): void;
    (e: 'focus', event: any): void;
    (e: 'blur', event: any): void;
}
