import { type CropImageAgentProps } from './common';
declare const _default: import("vue").DefineComponent<CropImageAgentProps, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<CropImageAgentProps> & Readonly<{}>, {
    complete: () => void;
    success: (filePath: string) => void;
    fail: (err: any) => void;
    cancel: () => void;
    rootStyle: string | false | import("vue").CSSProperties | import("vue").StyleValue[] | null;
    rootClass: string;
    type: "png" | "jpg";
    visible: boolean;
    id: string;
    duration: number;
    src: string;
    cropScale: string;
    quality: number;
    beforeCrop: (width: number, height: number) => number;
    cancelText: string;
    confirmText: string;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, false, {}, any>;
export default _default;
