import { type StyleValue } from 'vue';
import { type DatetimeRangePickerProps, type DatetimeRangePickerSlots } from '../datetime-range-picker/common';
import { type TransitionHookEmits } from '../popup/common';
export interface DatetimeRangePickerPopoutProps extends DatetimeRangePickerProps {
    visible?: boolean;
    title?: string;
    validateEvent?: boolean;
    popoutClass?: string;
    popoutStyle?: StyleValue;
    resettable?: boolean;
}
export declare const defaultDatetimeRangePickerInputProps: () => {
    visible?: (boolean | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => boolean)) | undefined;
    title?: (string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string)) | undefined;
    validateEvent?: (boolean | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => boolean)) | undefined;
    popoutClass?: (string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string)) | undefined;
    popoutStyle?: (string | false | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null) | undefined;
    resettable?: (boolean | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => boolean)) | undefined;
    modelValue?: ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => (string | Date)[]) | undefined;
    tabs?: ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string[]) | undefined;
    filter?: ((letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean) | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean) | undefined;
    min?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | Date) | undefined;
    max?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | Date) | undefined;
    rootStyle?: string | false | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string | false | import("vue").CSSProperties | StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string) | undefined;
    type?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string) | undefined;
    calendar?: "solar" | "lunar" | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => "solar" | "lunar") | undefined;
    formatter?: ((letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined) | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined) | undefined;
    valueFormat?: string | ((props: {
        visible: boolean;
        title: string;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: StyleValue;
        resettable: boolean;
        modelValue: (Date | string)[];
        tabs: string[];
        filter: (letter: import("../datetime-picker").DatetimeLetter, value: number, date: Date, index: number) => boolean;
        min: Date | string;
        max: Date | string;
        rootStyle: StyleValue;
        rootClass: string;
        type: string;
        calendar: "solar" | "lunar";
        formatter: (letter: import("../datetime-picker").DatetimeLetter, option: import("../datetime-picker").DatetimeColumnOption, date: Date, index: number) => string | void | undefined;
        valueFormat: string;
    }) => string) | undefined;
};
export interface DatetimeRangePickerPopoutSlots extends DatetimeRangePickerSlots {
}
export interface DatetimeRangePickerPopoutEmits extends TransitionHookEmits {
    (e: 'update:visible', visible: boolean): void;
    (e: 'update:model-value', date: (Date | string)[] | undefined): void;
    (e: 'change', date: (Date | string)[] | undefined): void;
    (e: 'confirm'): void;
}
export interface DatetimeRangePickerPopoutExpose {
}
