import { type CalendarPopoutEmits, type CalendarPopoutProps } from '../calendar-popout/common';
import { type PopoutInputSlots, type PopoutInputProps } from '../popout-input/common';
export interface CalendarInputProps extends CalendarPopoutProps, Omit<PopoutInputProps, 'modelValue' | 'loading'> {
    outletFormat?: string;
    valueOnClear?: () => any;
}
export declare const defaultCalendarInputProps: () => {
    outletFormat?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    valueOnClear?: ((() => any) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => any)) | undefined;
    visible?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    title?: string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    showConfirm?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    validateEvent?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    popoutClass?: string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutStyle?: string | false | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    resettable?: boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    rootStyle?: (string | false | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null) | undefined;
    rootClass?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    type?: (import("../calendar").CalendarType | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "multiple" | "single" | "range")) | undefined;
    modelValue?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | string[] | Date | Date[])) | undefined;
    min?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => Date) | undefined;
    max?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => Date) | undefined;
    currentDate?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => Date) | undefined;
    disabledDate?: (((date: Date) => boolean) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => (date: Date) => boolean)) | undefined;
    maxDays?: (number | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    overMaxDays?: ((() => void) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => void)) | undefined;
    weekStartsOn?: (number | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    formatter?: (((day: import("../calendar").CalendarDay) => void) | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => (day: import("../calendar").CalendarDay) => void)) | undefined;
    allowSameDay?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    severalMonths?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    valueFormat?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    startDateText?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    endDateText?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    sameDateText?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    disabled?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    clearable?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        outletFormat: string;
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        type: import("../calendar").CalendarType;
        modelValue: Date | Date[] | string | string[];
        min: Date;
        max: Date;
        currentDate: Date;
        disabledDate: (date: Date) => boolean;
        maxDays: number;
        overMaxDays: () => void;
        weekStartsOn: number;
        formatter: (day: import("../calendar").CalendarDay) => void;
        allowSameDay: boolean;
        severalMonths: boolean;
        valueFormat: string;
        startDateText: string;
        endDateText: string;
        sameDateText: string;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../input").InputProps) | undefined;
};
export interface CalendarInputSlots extends PopoutInputSlots {
}
export interface CalendarInputEmits extends CalendarPopoutEmits {
}
