import { type CheckboxGroupOption } from '../checkbox/common';
import { type PopoutInputSlots, type PopoutInputProps } from '../popout-input/common';
import { type CheckboxPopoutEmits, type CheckboxPopoutProps } from '../checkbox-popout/common';
export type CheckboxInputOption = CheckboxGroupOption;
export interface CheckboxInputProps extends CheckboxPopoutProps, Omit<PopoutInputProps, 'modelValue'> {
    valueOnClear?: () => any;
}
export declare const defaultCheckboxInputProps: () => {
    valueOnClear?: ((() => any) | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => any)) | undefined;
    visible?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    title?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    showCheckAll?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    searchable?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    filterPlaceholder?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    resettable?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    iconPosition?: "left" | "right" | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "left" | "right") | undefined;
    rootStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    modelValue?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => any[]) | undefined;
    disabled?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    readonly?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    size?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    type?: "circle" | "square" | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "circle" | "square") | undefined;
    checkedColor?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    direction?: "horizontal" | "vertical" | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => "horizontal" | "vertical") | undefined;
    validateEvent?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    options: (props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => CheckboxGroupOption[];
    optionKeys?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../checkbox/common").CheckboxGroupOptionKeys) | undefined;
    loading?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    clearable?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        showCheckAll: boolean;
        searchable: boolean;
        filterPlaceholder: string;
        resettable: boolean;
        iconPosition: "left" | "right";
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: any[];
        disabled: boolean;
        readonly: boolean;
        size: string;
        type: import("../checkbox/common").IconType;
        checkedColor: string;
        direction: "horizontal" | "vertical";
        validateEvent: boolean;
        options: CheckboxGroupOption[];
        optionKeys: import("../checkbox/common").CheckboxGroupOptionKeys;
        loading: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../input").InputProps) | undefined;
};
export interface CheckboxInputSlots extends PopoutInputSlots {
}
export interface CheckboxInputEmits extends CheckboxPopoutEmits {
}
