import { type PopoutInputSlots, type PopoutInputProps } from '../popout-input/common';
import { type CascaderPopoutProps, type CascaderPopoutEmits, type CascaderPopoutSlots } from '../cascader-popout/common';
export interface CascaderInputProps extends CascaderPopoutProps, Omit<PopoutInputProps, 'modelValue'> {
    valueOnClear?: () => any;
}
export declare const defaultCascaderInputProps: () => {
    valueOnClear?: ((() => any) | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => () => any)) | undefined;
    visible?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    title?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    showConfirm?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    validateEvent?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    popoutClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    popoutStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    resettable?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    rootStyle?: string | false | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | false | import("vue").CSSProperties | import("vue").StyleValue[]) | null | undefined;
    rootClass?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    modelValue?: string | number | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string | number | (string | number)[]) | undefined;
    options?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../cascader").CascaderOption[]) | undefined;
    fieldKeys?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../cascader").CascaderFieldKeys) | undefined;
    hintText?: string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string) | undefined;
    labelRender?: ((option: import("../cascader").CascaderOption) => string) | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => (option: import("../cascader").CascaderOption) => string) | undefined;
    changeOnSelect?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    allLevels?: boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean) | undefined;
    loading?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    disabled?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    readonly?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    placeholder?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    clearable?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    multiline?: (boolean | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => boolean)) | undefined;
    arrow?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    arrowFamily?: (string | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => string)) | undefined;
    internalArrow?: (number | ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => number)) | undefined;
    inputProps?: ((props: {
        valueOnClear: () => any;
        visible: boolean;
        title: string;
        showConfirm: boolean;
        validateEvent: boolean;
        popoutClass: string;
        popoutStyle: import("vue").StyleValue;
        resettable: boolean;
        rootStyle: import("vue").StyleValue;
        rootClass: string;
        modelValue: string | number | (string | number)[];
        options: import("../cascader").CascaderOption[];
        fieldKeys: import("../cascader").CascaderFieldKeys;
        hintText: string;
        labelRender: (option: import("../cascader").CascaderOption) => string;
        changeOnSelect: boolean;
        allLevels: boolean;
        loading: boolean;
        disabled: boolean;
        readonly: boolean;
        placeholder: string;
        clearable: boolean;
        multiline: boolean;
        arrow: string;
        arrowFamily: string;
        internalArrow: number;
        inputProps: import("../input").InputProps;
    }) => import("../input").InputProps) | undefined;
};
export interface CascaderInputSlots extends CascaderPopoutSlots, PopoutInputSlots {
}
export interface CascaderInputEmits extends CascaderPopoutEmits {
}
